//**
// TODO: Revisit for l10n and scalability
// */

const _redFlags = [
  'Argumentative',
  'Arrogant',
  'Combative',
  'Communication',
  'Competitive',
  'Conceited',
  'Condescending',
  'Conflict avoidant',
  'Defiant',
  'Disconnected',
  'Disorganised',
  'Dissatisifed',
  'Dominant',
  'Easily stressed',
  'Emotionally removed',
  'Extroverted',
  'Fear of failure',
  'Impatient',
  'Impulsive',
  'Indecisive',
  'Independent',
  'Inflexible',
  'Insecurity',
  'Insensitive',
  'Intense',
  'Intolerant',
  'Introverted ',
  'Jealousy',
  'Judgemental',
  'Low self-esteem',
  'Needy',
  'Opinionated',
  'Over-confident',
  'Over-thinking',
  'Overly accomodating',
  'Overly critical',
  'Overly empathetic',
  'Overly humble',
  'Overly-optimistic',
  'Overly-pessimistic',
  'Overly-sensitive',
  'Perfectionist',
  'Reluctant to change',
  'Reluctant to open up',
  'Reserved',
  'Risk-taker',
  'Self critical',
  'Shy',
  'Stubborn',
  'Unfocused',
  'Unpredictable',
  'Unstructured',
  'Vain',
];
const _greenFlags = [
  'Advice-giver',
  'Analytical',
  'Artistic',
  'Calm',
  'Charismatic',
  'Committed',
  'Communication',
  'Compassionate',
  'Competitive',
  'Confident',
  'Creative',
  'Curious',
  'Dedicated',
  'Determined',
  'Efficient',
  'Empathetic',
  'Energetic',
  'Funny',
  'Generous',
  'Hard working',
  'Honest',
  'Humble',
  'Humour',
  'Impulsive',
  'Independent',
  'Informed',
  'Knowledgeable',
  'Listening',
  'Logical',
  'Loyalty',
  'Observant',
  'Open-minded',
  'Optimistic',
  'Organised',
  'Original',
  'Passionate',
  'Patient',
  'Perceptive',
  'Perfectionist',
  'Practical',
  'Quick thinker',
  'Rational',
  'Reliable',
  'Responsible',
  'Risk-taker',
  'Selfless',
  'Sociable',
  'Spontaneous',
  'Strong-willed',
  'Supportive',
];

class FlagModel {
  FlagModel();

  static List<String> get redFlags => _redFlags;
  static List<String> get greenFlags => _greenFlags;
}
