// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nIrW_Hq8QoSJtUdTE8CyyLMuVMur71s',
    appId: '1:775764266894:android:3797c3595e512fdbb65edf',
    messagingSenderId: '775764266894',
    projectId: 'rf-app-dev-7145f',
    storageBucket: 'rf-app-dev-7145f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIeWtNdZYtR4tVN2a-1GaIJIIIu6UTpA',
    appId: '1:775764266894:ios:263869f4f788811db65edf',
    messagingSenderId: '775764266894',
    projectId: 'rf-app-dev-7145f',
    storageBucket: 'rf-app-dev-7145f.appspot.com',
    androidClientId:
        '775764266894-h42irtjoedoeac0qh6a1p33l771l19i1.apps.googleusercontent.com',
    iosClientId:
        '775764266894-13qbr357ueqb9kmntphvh66r9rec467q.apps.googleusercontent.com',
    iosBundleId: 'com.redflags.app.dev',
  );
}
